{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"【Python】構文とエラー .ipynb","provenance":[],"authorship_tag":"ABX9TyNAFKIQZ/8KBcwJgNihpD5F"},"kernelspec":{"name":"python3","display_name":"Python 3"}},"cells":[{"cell_type":"code","metadata":{"id":"Ce65x-mKWRgF","colab_type":"code","colab":{}},"source":["print(\"こんにちは)"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"6fFGZzSvWUSP","colab_type":"code","colab":{}},"source":["print(\"こんにちは\")"],"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"R0Twqt8rWXWx","colab_type":"code","colab":{}},"source":["4 / 0"],"execution_count":null,"outputs":[]}]}